name: Daily Download

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download file from dailybing.com
        run: |
          curl -o bing-image.jpg https://dailybing.com/image-url

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # 使用个人访问令牌
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated daily download from dailybing.com"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/shenhehetw/firest_repository.git HEAD:main
