name: Daily Download

on:
  schedule:
    # 每天凌晨 2 点运行（UTC 时间）
    - cron: '0 2 * * *'
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 从 dailybing.com 下载文件
      - name: Download file from dailybing.com
        run: |
          # 使用 curl 下载文件
          curl -o bing-image.jpg https://dailybing.com/image-url
          # 根据需要修改文件名和 URL 以适应不同类型的文件
          # 例如：curl -o daily-file.txt https://dailybing.com/file-url

      # 3. 提交并推送更改
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated daily download from dailybing.com"
          git push
